//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireVideothequeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENT
    {
        public int CLIENTID { get; set; }

        [Required]
        public string NOM { get; set; }

        [Required]
        public string PRENOM { get; set; }

        [Required]
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }

        [Required]
        public string NUMEROTEL { get; set; }

        [Required]
        public string ADRESSE { get; set; }

        [Required]
        public string MAIL { get; set; }
    }
}
