//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireVideothequeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public int FILMID { get; set; }
        public string NOMFILM { get; set; }
        public string CATEGORIE { get; set; }
        public string REALISATEUR { get; set; }
        public System.DateTime DATESORTIE { get; set; }
    }
}
